version: 2

jobs:
    build:
        docker:
            - image: nmarkgraf/python-pandoc:1.0
        steps:
            - checkout
            - run:
                name: Activate venv
                command: |
                    python3 -m venv ~/venv
                    source ~/venv/bin/activate
            - run:
                name: Update Python pip and install requirements (panflute)
                command: |
                    source ~/venv/bin/activate
                    pip install --upgrade pip
                    pip install panflute
            - run:
                name: Run tests
                command: |
                    source ~/venv/bin/activate
                    python3 -m unittest test/decorator_unittest.py
                    python3 -m unittest test/style_unittest.py
